name: Run Tests

on:
  repository_dispatch:
    types : [run_test_on_demand]
  pull_request:
    branches:
      - master-final
  push:
    branches:
      - master
      - master-final
      - feature/*
      - fix/*
      - features/*
      - bug/*
 
jobs:
  setup:
    name: Run tests on push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      uses: docker://docker/compose:1.22.0
      with:
        args: build --no-cache
    - name: Run tests
      run: |
        bash run_tests.sh
